### ISSUE TITLE
0.9.8 beta mac - if you commence editing and change your mind the application becomes unresponsive

### ISSUE THREAD

**Issue by j4jonathan** [raoulh/moolticute#133] opened 2017-10-19 08:27 UTC
If you commence editing an entry and then change your mind "Discard All Changes" doesn't do anything and the window becomes unresponsive. Screencast: https://cp.sync.com/dl/e00b45740#q7invwf4-uket794f-2krea3x5-ghaadst7

**Comment by limpkin** [comment] 2017-10-19 08:31
luckily you're here to test everything :)

**Comment by j4jonathan** [comment] 2017-10-19 08:36
Hahaha. I just bought a Mooltipass and am playing around with it. I've always felt the unspoken agreement with being a beta user was to help out by providing input. Let me know if it's annoying and I'll stop!

**Comment by limpkin** [comment] 2017-10-19 08:39
no no, please go ahead!

you're also welcome to talk with us on irc : #mooltipass on freenode.net

**Comment by raoulh** [comment] 2017-10-19 09:13
This is not a bug, you need to keep the "Discard All Changes" pressed to quit.

Also this is fixed in the next release.

**Closed by raoulh** 2017-10-19 09:13 UTC
